### ISSUE TITLE
Consider rewriting bindgen.sh completely in Rust

### ISSUE THREAD

**Issue by ian-h-chamberlain** [rust3ds/ctru-rs#113]
> As more of this is converted to Rust now I almost wonder if we should consider writing the other logic that I just added for `libctru` version numbering into `bindgen-ctru-sys` as well... Doesn't need to be part of this PR just something to think about

_Originally posted by @ian-h-chamberlain in https://github.com/rust3ds/ctru-rs/pull/110#discussion_r1157794014_

Windows support seems to be a pretty solid reason to fix this (although without `pacman`, we'll have to figure out if there's any reasonable way to query `libctru` version). We could always leave the `bindgen.sh` around as a convenience wrapper for `cargo run` too, if we want.

**Comment by Techie-Pi** [comment]
I think #125 fixed this
