### ISSUE TITLE
Cannot build, '3dsx.specs': No such file or directory

### ISSUE THREAD

**Issue by hen6003** [rust3ds/ctru-rs#131]
I cannot build the examples and get this error:
```
  = note: arm-none-eabi-gcc: fatal error: cannot read spec file '3dsx.specs': No such file or directory
```
presumably referring to this file
```
/opt/devkitpro/devkitARM/arm-none-eabi/lib/3dsx.specs
```
I can fix it by copying that file into the directory, but then I get more errors to do with libc, libm, and 3dsx_crt0.o.

Am I doing something wrong?

**Comment by Meziu** [comment]
Did you correctly [install](https://github.com/rust3ds/ctru-rs/wiki/Getting-Started#install-the-devkitarm-toolchain) the dkP toolchain? It seems like you are missing most of the needed packages.

If you did install devkitARM and `3ds-dev` correctly, I suggest you to check for your current `arm-none-eabi-gcc`, as I stated [here](https://github.com/orgs/rust3ds/discussions/130).

**Comment by hen6003** [comment]
I have been making stuff in C find, I do have `arm-none-eabi-gcc` here:
```
/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc
```

**Comment by hen6003** [comment]
Setting `export PATH="/opt/devkitpro/devkitARM/bin/":$PATH` fixed the issue, thanks for the help/pointers!
