### ISSUE TITLE
Outdated for libctru v2.3.1-1

### ISSUE THREAD

**Issue by lilrosalyn** [rust3ds/ctru-rs#143]
This warning occurs when building.
```
warning: ctru-sys@22.2.0+2.2.2-1: failed to check libctru version: libctru version is 2.3.1-1 but this crate was built for 2.2.2-1
```

For the time being, is it possible to downgrade the `3ds-dev` group to the supported version? I attempted `sudo dkp-pacman -S libctru=2.2.2-1` but it yielded a package not found error.

e: my build is failing, but after further investigation it seems possible that it is not failing due to a version mismatch but rather just missing clang libraries c:

**Comment by lilrosalyn** [comment]
build was indeed failing because clang was not installed

**Comment by ian-h-chamberlain** [comment]
Yeah, that warning (which should never prevent building) should go away with #141 which should hopefully make it more clear when there is a build failure for other reasons.

I guess I didn't realize that clang was required for building the crate, with `bindgen` as a build dependency! We should probably include a link to https://rust-lang.github.io/rust-bindgen/requirements.html somewhere in our "Getting started" documentation to make it more clear.

Edit: added a brief new wiki section https://github.com/rust3ds/ctru-rs/wiki/Getting-Started#install-llvm-for-bindgen
