### ISSUE TITLE
Adding a Docker Image as option for development

### ISSUE THREAD

**Issue by nandolawson** [rust3ds/ctru-rs#194]
A Docker Image / Devcontainer would make things way easier to setup. [I've already made one](https://github.com/nandolawson/rust-3ds). Feel free to use it in your documentation.

**Comment by Meziu** [comment]
That’s great! We received many complaints over time from people who were unable to setup the dev environment, so it’s nice to see a streamlined solution proposed as a dev container (we have our own in CI, but they aren’t meant for users). I support this 👍
