### ISSUE TITLE
Use `userAppInit` and `userAppExit` for runtime setup and takedown

### ISSUE THREAD

**Issue by FenrirWolf** [rust3ds/ctru-rs#53]
Fun fact, `libctru` supports life before and after `main` in the [appInit](https://github.com/devkitPro/libctru/blob/master/libctru/source/system/appInit.c) and [appExit](https://github.com/devkitPro/libctru/blob/master/libctru/source/system/appExit.c) functions. You can hook into this system by defining `extern "C" fn userAppInit()` and `extern "C" fn userAppExit()` functions and putting any* library-level setup/teardown code you want in them.

*Well, some things in the Rust stdlib aren't safe to call before or after main. But 3DS service initialization and even panic hook registration should be fine to do there.

**Comment by Meziu** [comment]
Oh, this means we could avoid the call to `ctru::init` at the start of programs. I didn’t know about this, great!

**Comment by FenrirWolf** [comment]
Hmm, that's unfortunate. It's also possible to override `appInit` and `appExit` themselves, and I wonder if that would work better since libctru calls those unconditionally. I'd try it out myself but I haven't worked out what the build process for the project is yet

**Comment by AzureMarker** [comment]
One downside of using this feature is that then users can't use this, since the symbol would already be defined.

**Comment by AzureMarker** [comment]
> I'd try it out myself but I haven't worked out what the build process for the project is yet

It's pretty much take the rust-horizon rustc fork, compile locally and add to rustup, then use cargo-3ds for building and stuff. Plus the devkitpro installation. We should probably write this up somewhere.

**Comment by FenrirWolf** [comment]
> We should probably write this up somewhere.

That would be good. I've already run into issues getting the thing to build so a place to talk about that would be nice too

**Comment by Meziu** [comment]
> One downside of using this feature is that then users can't use this, since the symbol would already be defined.

We could add our own safe hook, though for now it doesn’t matter.

**Comment by Meziu** [comment]
> > We should probably write this up somewhere.
> 
> That would be good. I've already run into issues getting the thing to build so a place to talk about that would be nice too

We were waiting for Rust to merge our changes before making wikis, this way people would be able to just use `cargo 3ds` on a nightly toolchain and be able to compile.

**Comment by AzureMarker** [comment]
We could enable and use the GitHub discussions feature in the meantime.

**Comment by Meziu** [comment]
It may work now, but due to the uncertainty of using the `std` outside the main and wanting to leave the possibility of customization to the user, this issue is now obsolete. Didn't think I'd ever close this! 😄
