### ISSUE TITLE
ctru-rs uses path to link to ctru-sys making it impossible to build

### ISSUE THREAD

**Issue by adryzz** [rust3ds/ctru-rs#88]
Tried making a simple app.

- Added this in the `Cargo.toml` file, in order to use it as a package, and added `ctru::init()` in the entrypoint.
```toml
[dependencies]
ctru-rs = { git = "https://github.com/Meziu/ctru-rs.git" }
```

When building though, i get the following error:

```
error: failed to select a version for `ctru-sys`.
    ... required by package `linker-fix-3ds v0.1.0 (https://github.com/rust3ds/rust-linker-fix-3ds.git#ed1ec9c7)`
    ... which satisfies git dependency `linker-fix-3ds` of package `ctru-rs v0.7.1 (https://github.com/Meziu/ctru-rs.git#2bc31ca9)`
    ... which satisfies git dependency `ctru-rs` of package `ctr-irc v0.1.0 (/home/adryzz/ctr-irc)`
versions that meet the requirements `*` are: 0.4.1
```
So i went and looked at why this issue was there, and found this.
https://github.com/rust3ds/ctru-rs/blob/2bc31ca9f354db8df352e55dc2983de34ad1782b/ctru-rs/Cargo.toml#L16

Then i cloned this repo along with `linker-fix-3ds` and `pthread-3ds`, and changed all the `Cargo.toml` files to point to a single `ctru-sys`, and it builds and runs successfully.

If all the packages used git to link to each other, it would build successfully.

(P.S. this project is great!)

**Comment by Meziu** [comment]
Closed as #89
