### ISSUE TITLE
Create a safe SVC module

### ISSUE THREAD

**Issue by Meziu** [rust3ds/ctru-rs#99]
`svc` is one of the most unsafe and dangerous interfaces of the 3DS' system. However, thanks to the current state of thing in the Rust ecosystem, we could do great things by implementing the `svc` wrapper to use Rust's `async/await`syntax.

This has the potential become one of the strong points of our toolchain. Nontheless, development is impaired by the lack of threading support.

**Comment by DeltaF1** [comment]
(I'm assuming the async/await stuff you're talking about would be wrapping over services/IPC. Sorry if this is the wrong place to ask about this)

I've been reading 3dbrew trying to learn about how IPC works, and looking at some [example code](https://github.com/PabloMK7/ctr-led-brary/blob/master/source/ctr-led-brary.cpp) online. It looks like [`getThreadCommandBuffer`](https://libctru.devkitpro.org/svc_8h.html#a2e0c230a1bb2d5400edc08bd7c687099) is necessary for constructing IPC commands but is not exposed in ctru-sys. How are things included/excluded from the bindings?

**Comment by Meziu** [comment]
> (I'm assuming the async/await stuff you're talking about would be wrapping over services/IPC. Sorry if this is the wrong place to ask about this)

It is the wrong place (no worries though). I was talking specifically about the `srv` module.

> I've been reading 3dbrew trying to learn about how IPC works, and looking at some [example code](https://github.com/PabloMK7/ctr-led-brary/blob/master/source/ctr-led-brary.cpp) online. It looks like [`getThreadCommandBuffer`](https://libctru.devkitpro.org/svc_8h.html#a2e0c230a1bb2d5400edc08bd7c687099) is necessary for constructing IPC commands but is not exposed in ctru-sys. How are things included/excluded from the bindings?

It seems the `ctru-sys` currently in master was built with a bindgen older than [this](https://github.com/rust-lang/rust-bindgen/pull/2335) PR, so `static inline` functions (like `getThreadCommandBuffer`) weren't included. We should update `ctru-sys`.

**Comment by DeltaF1** [comment]
Could you elaborate more about your vision for this? I'm still confused about which parts of `svc` you're thinking of.

**Comment by Meziu** [comment]
After further research, this issue seems mostly impossible/out-of-scope/still to determine/unnecessary. If I find the right inspiration and ideas about something similar I'll open a more specific PR.
